const adjektiv = [
    {
        adjektiv: "verärgert",
        meaning: "annoy, upset",
        english_sentence: "The boss thinks that her employees do a bad job. That's why she's upset.",
        german_sentence: "Die Chefin findet, dass ihre Mitarbeiter schlecht arbeiten. Deshalb ist sie verärgert.",
        remark: "https://quizlet.com/695528147/flashcards",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "hilfsbereit",
        meaning: "helpful",
        english_sentence: "My colleagues often help me. They are very helpful.",
        german_sentence: "Meine Kollegen helfen mir oft. Sie sind sehr hilfsbereit.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "nervös",
        meaning: "nervous",
        english_sentence: "Before a job interview, many people are very nervous.",
        german_sentence: "Vor einem Bewerbungsgespräch sind viele Leute sehr nervös.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "streng",
        meaning: "strict",
        english_sentence: "Our teacher at the vocational school is nice but strict.",
        german_sentence: "Unsere Lehrerin in der Berufsschule ist nett, aber streng.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "elegant",
        meaning: "elegant",
        english_sentence: "Mr. Jankowski always wears clothes that are very elegant.",
        german_sentence: "Herr Jankowski trägt immer Kleidung, die sehr elegant ist.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "gepflegt",
        meaning: "neat, trim, well-groomed",
        english_sentence: "My daughter is very careful about her appearance and hygiene. She is very well cared for.",
        german_sentence: "Meine Tochter achtet sehr auf ihr Aussehen und ihre Hygiene. Sie ist sehr gepflegt.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "unangemessen",
        meaning: "inappropriate",
        english_sentence: "Coming to an interview in shorts is inappropriate.",
        german_sentence: "Zu einem Bewerbungsgespräch in Shorts zu kommen, ist unangemessen.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "zufrieden",
        meaning: "satisfied",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "fleißig",
        meaning: "hard-working",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "ehrgeizig",
        meaning: "ambitious",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "aufmerksam",
        meaning: "attentive",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "unaufmerksam",
        meaning: "inattentive",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "ungeduldig",
        meaning: "impatient",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "sympathisch",
        meaning: "friendly",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "schlecht gelaunt",
        meaning: "in a bad mood",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "freundlich",
        meaning: "friendly",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "entspannt",
        meaning: "relaxed",
        english_sentence: "Then you can do sports and relax.",
        german_sentence: "Da kannst du dann auch Sport machen und entspannen.",
        remark: "",
        chapter: "b1-7",
        create_date: "02/08/2022",
        update_date: "02/08/2022",
    },
    {
        adjektiv: "gelangweilt",
        meaning: "bored",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "02/08/2022",
        update_date: "02/08/2022",
    },
    {
        adjektiv: "ruhig",
        meaning: "calm",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "genervt",
        meaning: "annoyed",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "höflich",
        meaning: "polite",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "interessiert",
        meaning: "Interested",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "desinteressiert",
        meaning: "disinterested",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "aufgeregt",
        meaning: "excited",
        english_sentence: "I am not sleeping because I am very excited.",
        german_sentence: "Ich schlafe nicht, denn ich bin sehr aufgeregt.",
        remark: "",
        chapter: "duolingo",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "ganz",
        meaning: "whole, total, full",
        english_sentence: "Do you have to work whole day?",
        german_sentence: "Musst du den ganzen Tag arbeiten?",
        remark: "",
        chapter: "duolingo",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "nass",
        meaning: "wet",
        english_sentence: "Why is it wet in the car?",
        german_sentence: "Warum ist es nass im Auto?",
        remark: "",
        chapter: "duolingo",
        create_date: "17/07/2022",
        update_date: "17/07/2022",
    },
    {
        adjektiv: "unendlich",
        meaning: "infinite",
        english_sentence: "This movie never ends. It's infinitely long.",
        german_sentence: "Dieser Film nimmt kein Ende. Er ist unendlich lang.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "besonders",
        meaning: "special",
        english_sentence: "I like to eat almost everything, but I especially / especially like green curry.",
        german_sentence: "Ich esse fast alles gern, aber vor allem / besonders mag ich Grünes Curry.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "steigen",
        meaning: "rise",
        english_sentence: "Tomorrow it will be warmer again. The temperatures are rising.",
        german_sentence: "Morgen wird es wieder wärmer. Die Temperaturen steigen.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "zunehmen",
        meaning: "increase",
        english_sentence: "During the corona pandemic, almost no tourists came to Thailand. Now the number is increasing again.",
        german_sentence: "Während der Corona-Pandemie kamen fast keine Touristen mehr nach Thailand. Jetzt nimmt die Zahl wieder zu.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "beeindruckend",
        meaning: "impressive",
        english_sentence: "It's impressive how quickly you learned German.",
        german_sentence: "Es ist beeindruckend, wie schnell du Deutsch gelernt hast.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "bereit",
        meaning: "ready",
        english_sentence: "I have already eaten. = I have already eaten.",
        german_sentence: "Ich habe schon gegessen. = Ich habe bereits gegessen.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "reif",
        meaning: "frost, hoarfrost, rime, ferrule",
        english_sentence: "These strawberries are not yet ready to eat.",
        german_sentence: "Diese Erdbeeren kann man noch nicht essen. Sie ist noch nicht reif.",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "anstrengend",
        meaning: "exhausting, tiring",
        english_sentence: "That's too tiring!",
        german_sentence: "Das ist mit zu anstrengend!",
        remark: "",
        chapter: "b1-7",
        create_date: "02/08/2022",
        update_date: "02/08/2022",
    },
    {
        adjektiv: "rein",
        meaning: "pure, clean",
        english_sentence: "A pure city tour is too much.",
        german_sentence: "Eine reine Städtetour ist zu viel. ",
        remark: "",
        chapter: "b1-7",
        create_date: "02/08/2022",
        update_date: "02/08/2022",
    },
    {
        adjektiv: "aktuell",
        meaning: "current, up-to-date, latest",
        english_sentence: "Here are the current traffic reports.",
        german_sentence: "Hier sind die aktuellen Verkehrsmeldungen.",
        remark: "",
        chapter: "b1-7",
        create_date: "02/08/2022",
        update_date: "02/08/2022",
    },
    {
        adjektiv: "gesperrt",
        meaning: "blocked",
        english_sentence: "The right lane is closed.",
        german_sentence: "der rechte Fahrstreifen ist gesperrt.",
        remark: "",
        chapter: "b1-7",
        create_date: "02/08/2022",
        update_date: "02/08/2022",
    },
    {
        adjektiv: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
    {
        adjektiv: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-4",
        create_date: "14/07/2022",
        update_date: "14/07/2022",
    },
]




module.exports = {
    adjektiv: adjektiv,
}