const adjektiv = [
    { 
        artikel: "der",
        wort: "Name",
        plural: "Namen",
        meaning: "name",
        english_sentence: "What is your name? (Formal)",
        german_sentence: "Wie ist Ihr Name? (Formell)",
        remark: "",
        chapter: "a1-1",
        create_date: "02/06/2022",
        update_date: "02/06/2022",
    },
    {
        artikel: "die",
        wort: "Vorlesung",
        plural: "Vorlesungen",
        meaning: "lecture",
        english_sentence: "Today at 10:30 a.m. he has a lecture with Professor Strasser.",
        german_sentence: "Heute hat er um 10:30 Uhr eine Vorlesung bei Professor Strasser.",
        remark: "",
        chapter: "a1-9",
        create_date: "04/06/2022",
        update_date: "04/06/2022",
    },
    {
        artikel: "die",
        wort: "Präsentation",
        plural: "Präsentationen",
        meaning: "presentation",
        english_sentence: "She is planning a presentation.",
        german_sentence: "Sie planen eine Präsentation.",
        remark: "",
        chapter: "a1-9",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Mode",
        plural: "Moden",
        meaning: "Fashion",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Kleidung",
        plural: "Kleidungen",
        meaning: "clothes",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Pullover",
        plural: "Pullover",
        meaning: "Pullover, Sweater",
        english_sentence: "What do you think of the sweater? - Which one?(this one.)",
        german_sentence: "Wie findest du den Pullover? - Welchen?(diesen hier.)",
        remark: "Pulli",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Anzug",
        plural: "Anzüge",
        meaning: "men's suit",
        english_sentence: "Which suit is better?",
        german_sentence: "Welcher Anzug ist besser?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Rock",
        plural: "Röcke",
        meaning: "skirt",
        english_sentence: "How do you like the skirt - Which one? (this one.)",
        german_sentence: "Wie gefällt dir der Rock? - Welcher?(dieser hier.)",
        remark: "Rouge",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Gürtel",
        plural: "Gürtel",
        meaning: "belt",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Rollkragenpullover",
        plural: "Rollkragenpullover",
        meaning: "turtleneck",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Langer Cardigan",
        plural: "Langer Cardigans",
        meaning: "Cardigan",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Mantel mit Kapuze",
        plural: "Mäntel mit Kapuze",
        meaning: "Coat with hood",
        english_sentence: "What coat are you wearing?",
        german_sentence: "Welchen Mantel ziehst du an?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Parka mit Teddyfutter",
        plural: "Parkas",
        meaning: "Parka",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Bucket-Hut aus Wolle",
        plural: "Hüte",
        meaning: "Hat",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Filzhut",
        plural: "Filzhüte",
        meaning: "Hut",
        english_sentence: "-",
        german_sentence: "-",
        remark: "Oktoberfest",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "das",
        wort: "Hemd",
        plural: "Hemden",
        meaning: "shirt",
        english_sentence: "Which shirt would you like to try on?",
        german_sentence: "Welches Hemd möchtest du anprobieren?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "das",
        wort: "T-Shirt",
        plural: "T-Shirts",
        meaning: "T-Shirt",
        english_sentence: "Which t-shirt suits me?",
        german_sentence: "Welches T-Shirt steht mir?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "das",
        wort: "Kapuzenshirt",
        plural: "Kapuzenshirts",
        meaning: "T-Shirt with hood",
        english_sentence: "-",
        german_sentence: "-",
        remark: "Shirt in german is T-shirt",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "das",
        wort: "Sweatshirt",
        plural: "Sweatshirts",
        meaning: "sweatshirt",
        english_sentence: "-",
        german_sentence: "-",
        remark: "เสื้อshirt ที่หนาขึ้น",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "das",
        wort: "Kleid",
        plural: "Kleider",
        meaning: "Dress",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "das",
        wort: "Tuch",
        plural: "Tücher",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "Schal for winter, Tuch for summer",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Tasche",
        plural: "Taschen",
        meaning: "bag",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Jacke",
        plural: "Jacken",
        meaning: "coat, jacket for woman",
        english_sentence: "Look, the jacket is great! - Which one?(This one.)",
        german_sentence: "Sieh mal, die Jacke ist doch toll! - Welche?(Diese hier.)",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Jacke",
        plural: "Jacken",
        meaning: "coat, jacket for woman",
        english_sentence: "Which jacket do you like?",
        german_sentence: "Welche Jacke findest du gut?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Bluse",
        plural: "Blusen",
        meaning: "blouse",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Hose",
        plural: "Hosen",
        meaning: "trousers",
        english_sentence: "Which pants do you not like?",
        german_sentence: "Welche Hose findest du nicht gut?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Jeans",
        plural: "Jeans",
        meaning: "Jeans",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Mütze",
        plural: "Mützen",
        meaning: "tuque (hat)",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Puffer Jacket",
        plural: "Puffer Jacket",
        meaning: "Puffer Jacket",
        english_sentence: "-",
        german_sentence: "-",
        remark: "ใส่แล่้วตัวบวมบวม",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Kappe",
        plural: "Kappen",
        meaning: "Cap",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der(PL)",
        wort: "Sportschuh",
        plural: "Sportschuhe",
        meaning: "sports shoe",
        english_sentence: "-",
        german_sentence: "-",
        remark: "ADIDAS, NIKE",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Schuh",
        plural: "Schuhe",
        meaning: "Shoes",
        english_sentence: "The shoes are terrible - Which ones? (These ones.)",
        german_sentence: "Die Schuhe sind schrecklich - Welche?(diese hier.)",
        remark: "Lederchuhe (หนัง)",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Strumpf",
        plural: "Strümpfe",
        meaning: "stocking, Legging",
        english_sentence: "Which stockings do you mean?",
        german_sentence: "Welche Strümpfe meinst du?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Stiefel",
        plural: "Stiefel",
        meaning: "boot",
        english_sentence: "I’ll take the boots - which one?(this one.)",
        german_sentence: "Ich nehme die Stiefel. - Welche?(diese hier.)",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Stiefel",
        plural: "Stiefel",
        meaning: "boot",
        english_sentence: "Which boots do you like better?",
        german_sentence: "Welche Stiefel findest du besser?",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Socke",
        plural: "Socken",
        meaning: "Sock",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Pumps",
        plural: "Pumps",
        meaning: "ส้นสูง",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Sandalette",
        plural: "Sandaletten",
        meaning: "sandal",
        english_sentence: "-",
        german_sentence: "-",
        remark: "letten = มีส้น",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Sandale",
        plural: "Sandalen",
        meaning: "sandal",
        english_sentence: "",
        german_sentence: "",
        remark: "Sandaletten > Sandalen",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "die",
        wort: "Seite",
        plural: "Seiten",
        meaning: "Page",
        english_sentence: "Go to the page",
        german_sentence: "Gehen Sie mal auf die Seite",
        remark: "-",
        chapter: "a1-10",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    { 
        artikel: "die",
        wort: "Aushilfe",
        plural: "Aushilfen",
        meaning: "Temporary help",
        english_sentence: "We're looking for a temp.",
        german_sentence: "Wir suchen eine Aushilfe.",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die", 
        wort: "Wand",
        plural: "Wände",
        meaning: "Wall",       
        english_sentence: "The picture is on the wall.",                 
        german_sentence: "Das Bild hängt an der Wand.",
        remark: "Dativ, Wo",
        chapter: "a2-2",
        create_date: "10/05/2022",
        update_date: "10/05/2022",            
    },
    { 
        artikel: "die",
        wort: "Wand",
        plural: "Wände",
        meaning: "Wall",
        english_sentence: "I hang the picture on the wall.",
        german_sentence: "Ich hänge das Bild an die Wand.",
        remark: "Akku, Wohin",
        chapter: "a2-2",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Lied",
        plural: "Lieder",
        meaning: "Song",
        english_sentence: "What do you think of the song?",
        german_sentence: "Wie findest du das Lied?",
        remark: "",
        chapter: "a2-4",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Lied",
        plural: "Lieder",
        meaning: "Song",
        english_sentence: "We play five seconds from a current top ten CD and you name the song.",
        german_sentence: "Wir spielen fünf Sekunden von einer aktuellen Top-Ten-CD und Sie nennen uns das Lied.",
        remark: "",
        chapter: "a2-4",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Erfahrung",
        plural: "-en",
        english_sentence: "Experiences in a foreign country",
        german_sentence: "Erfahrungen im fremden Land"
    },
    { 
        artikel: "der", 
        wort: "Teilnehmer",
        plural: "-",          
        english_sentence: "The participants in my course are almost always on time.",                 
        german_sentence: "Die Teilnehmer in meinem Kurs sind fast immer pünktlich."                 
    },
    { 
        artikel: "der", 
        wort: "Führerschein",
        plural: "-e",
        meaning: "driver's license",
        english_sentence: "I have lost my driver's license.",
        german_sentence: "Ich bin meinen Führerschein los.",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der", 
        wort: "Führerschein",
        plural: "-e",
        meaning: "driver's license",
        english_sentence: "Does anyone of you have a driving license?",
        german_sentence: "Hat jemand von euch einen Führerschein?",
        remark: "",
        chapter: "",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    { 
        artikel: "die",
        wort: "Führerscheinprüfung",
        plural: "-en",
        meaning: "driving test",
        english_sentence: "Have you passed your driving test?",
        german_sentence: "Hast du deine Führerscheinprüfung bestanden?",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der", 
        wort: "Schulabschluss",
        plural: "-ü e",          
        english_sentence: "I have been with him since I got out of high school(graduation)",                 
        german_sentence: "Ich bin seit dem Schulabschluss bei ihm"                 
    },
    { 
        artikel: "der", 
        wort: "Motor",
        plural: "-en",          
        english_sentence: "I think the engine’s broken.",                 
        german_sentence: "Ich glaube, der Motor ist kaputt.",
        chapter: "a2-6",
    },
    { 
        artikel: "die",
        wort: "Reparatur",
        plural: "-en",
        meaning: "Repair",
        english_sentence: "the repair will be expensive.",
        german_sentence: "Die Reparatur wird bestimmt teuer.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Unfall",
        plural: "ä e",
        meaning: "Accident",
        english_sentence: "And what if I have an accident on vacation?",
        german_sentence: "Und was ist, wenn ich im Urlaub einen Unfall habe?",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Baustelle",
        plural: "Baustellen",
        meaning: "Construction Site",
        english_sentence: "And what if I have an accident on vacation?",
        german_sentence: "Gehen Sie über die Straße und dann um die Baustelle herum.",
        remark: "",
        chapter: "",
        create_date: "29/05/2022",
        update_date: "29/05/2022",
    },
    { 
        artikel: "die", 
        wort: "Versicherung",
        plural: "-en",          
        english_sentence: "Well, usually the insurance pays for it.",                 
        german_sentence: "Na ja, normalerweise bezahlt das die Versicherung.",
        chapter: "a2-6",           
    },
    { 
        artikel: "die",
        wort: "Reise",
        plural: "-n",
        meaning: "Travelling",
        english_sentence: "Travelling by train is too expensive for her, but she doesn’t have a car.",
        german_sentence: "Die Reise mit dem Zug ist ihr zu teuer, aber sie hat kein Auto",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Rad",
        plural: "ä er",
        meaning: "bike",
        english_sentence: "She likes to ride a bike",
        german_sentence: "Sie fährt gern Rad.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Motorrad",
        plural: "Motorräder",
        meaning: "motorcycle",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-6",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    { 
        artikel: "der",
        wort: "Kreis",
        plural: "-e",
        meaning: "circle",
        english_sentence: "You sit in a circle.",
        german_sentence: "Sie sitzen im Kreis.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Weg",
        plural: "-e",
        meaning: "circle",
        english_sentence: "The fast way through the city.",
        german_sentence: "Der schnelle Weg durch die Stadt.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Lösung",
        plural: "-en",
        meaning: "solution",
        english_sentence: "We have the solution",
        german_sentence: "Wir haben die Lösung",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Wohnungsschlüssel",
        plural: "-",
        meaning: "Apartment key",
        english_sentence: "I forgot my apartment key!",
        german_sentence: "Ich habe meinen Wohnungsschlüssel vergessen!",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Verkehrsmittel",
        plural: "-",
        meaning: "Means of transport",
        english_sentence: "Which means of transport is the fastest?",
        german_sentence: "Welches Verkehrsmittel ist am schnellsten?",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Verkehrsmittel",
        plural: "-",
        meaning: "Means of transport",
        english_sentence: "Which means of transport do you use?",
        german_sentence: "Welches Verkehrsmittel benutzen Sie?",
        remark: "",
        chapter: "a2-6",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    { 
        artikel: "das",
        wort: "Verkehrsmittel",
        plural: "-",
        meaning: "Means of transport",
        english_sentence: "So please come either by public transport or park at the north entrance.",
        german_sentence: "Bitte kommen Sie also entweder mit den öffentlichen Verkehrsmitteln oder parken Sie am Eingang Nord.",
        remark: "",
        chapter: "a2-6",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    { 
        artikel: "die",
        wort: "Bushaltestelle",
        plural: "-n",
        meaning: "bus stop",
        english_sentence: "I’ve been waiting at the bus stop for half an hour.",
        german_sentence: "Ich warte schon eine halbe Stunde an der Bushaltestelle.",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Kinderspielplatz",
        plural: "-ä e",
        meaning: "children's playground",
        english_sentence: "Lilly and Felix must be at the children's playground.",
        german_sentence: "Lilly und Felix sind bestimmt auf dem Kinderspielplatz.",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Vertrag",
        plural: "-ä e",
        meaning: "contract, agreement",
        english_sentence: "none",
        german_sentence: "none",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Ersatzteil",
        plural: "e",
        meaning: "spare part",
        english_sentence: "none",
        german_sentence: "none",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Hochseilgarten",
        plural: "ä",
        meaning: "high ropes course",
        english_sentence: "The professionals from the high ropes course explain the rules to the people very well.",
        german_sentence: "Die Profis vom Hochseilgarten erklären den Leuten die Regeln sehr gut.",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Besucher",
        plural: "Besucher",
        meaning: "Visitor",
        english_sentence: "They give the visitors helmets.",
        german_sentence: "Sie geben den Besuchern Helme.",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Helm",
        plural: "Helme",
        meaning: "Helmet",
        english_sentence: "They give the visitors helmets.",
        german_sentence: "Sie geben den Besuchern Helme.",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Brief",
        plural: "Briefe",
        meaning: "letter",
        english_sentence: "Mrs.Korkmaz sends a letter to a man.",
        german_sentence: "Frau Korkmaz schickt einem Mann einen Brief.",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Spielzeug",
        plural: "-",
        meaning: "toys",
        english_sentence: "Does Tom give his child a toy?",
        german_sentence: "Schenkt Tom seinem Kind ein Spielzeug?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Schal",
        plural: "Schals/Schale",
        meaning: "Scarf",
        english_sentence: "Does Tom give his mother a scarf?",
        german_sentence: "Schenkt Tom seiner Mutter einen Schal?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Schminkspiegel",
        plural: "Schminkspiegel",
        meaning: "Makeup mirror",
        english_sentence: "Does Tom give his sister a make-up mirror?",
        german_sentence: "Schenkt Tom seiner Schwester einen Schminkspiegel?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Marketasche",
        plural: "Marketaschen",
        meaning: "branded bag",
        english_sentence: "Does Tom give his wife a branded bag?",
        german_sentence: "Schenkt Tom seiner Frau eine Marketasche?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Brücke",
        plural: "Brücken",
        meaning: "Bridge",
        english_sentence: "Lara walks past the bridge.",
        german_sentence: "Lara geht an der Brücke vorbei.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Fluss",
        plural: "Flüsse",
        meaning: "River",
        english_sentence: "She goes to the river",
        german_sentence: "Sie geht bis zum Fluss",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "See",
        plural: "Seen",
        meaning: "Lake",
        english_sentence: "Lake",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "See",
        plural: "Seen",
        meaning: "Sea",
        english_sentence: "Sea",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Gebäude",
        plural: "Gebäude",
        meaning: "Building",
        english_sentence: "In our building there are over 100 apartments.",
        german_sentence: "In unserem Gebäude gibt es über 100 Wohnungen.",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Nachbar",
        plural: "Nachbarn",
        meaning: "Neighbour",
        english_sentence: "Funny, when you don't know your neighbors.",
        german_sentence: "Komisch, wenn man seine Nachbarn nicht kennt.",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Das",
        wort: "Getränk",
        plural: "Getränke",
        meaning: "drinks, beverage",
        english_sentence: "Can you buy drinks for the picnic?",
        german_sentence: "Kannst du Getränke für das Picknick kaufen?",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Das",
        wort: "Geschäft",
        plural: "Geschäfte",
        meaning: "Store",
        english_sentence: "Are the shops open?",
        german_sentence: "Sind die Geschäfte geöffnet?",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Das",
        wort: "Hausboot",
        plural: "Hausboote",
        meaning: "Houseboat",
        english_sentence: "Our houseboat is just as big as our old apartment.",
        german_sentence: "Unser Hausboot ist aber genauso groß wie unsere alte Wohnung.",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Bauernhof",
        plural: "Bauernhöfe",
        meaning: "Farm, Barnyard",
        english_sentence: "Life on the farm means a lot of work, but it’s great.",
        german_sentence: "Das Leben auf dem Bauernhof bedeutet viel Arbeit , aber es ist toll.",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Das",
        wort: "Tier",
        plural: "Tiere",
        meaning: "Animal",
        english_sentence: "We live in the countryside and have many animals.",
        german_sentence: "Wir leben auf dem Land und habe viele Tiere.",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Einwohner",
        plural: "Einwohner",
        meaning: "Inhabitant, resident, habitant, population",
        english_sentence: "In my city, there are 4 million inhabitants.",
        german_sentence: "In meiner Stadt gibt es 4 Millionen Einwohner.",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Die",
        wort: "Insel",
        plural: "Inseln",
        meaning: "Island",
        english_sentence: "On our small island there is no supermarket.",
        german_sentence: "Auf unserer kleinen Insel gibt es keinen Supermarkt.",
        remark: "",
        chapter: "a2-9",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "Das",
        wort: "Dach",
        plural: "Dächer",
        meaning: "Roof",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Flur",
        plural: "Flure",
        meaning: "Hallway, Corridor",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Der",
        wort: "Gang",
        plural: "Gänge",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "any type of corridor, it can also be used for an underground passage or for a passageway enclosed by fences.",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Garten",
        plural: "Gärten",
        meaning: "Garden",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Die",
        wort: "Terrasse",
        plural: "Terrassen",
        meaning: "Terrace",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Die",
        wort: "Treppe",
        plural: "Treppen",
        meaning: "stairs",
        english_sentence: "in a high-rise building with an elevator, you don't have to use the stairs.",
        german_sentence: "In einem Hochhaus mit Aufzug muss man nicht die Treppen benutzen.",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Die",
        wort: "Garage",
        plural: "Garagen",
        meaning: "Garage",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Keller",
        plural: "Keller",
        meaning: "Basement",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Müll",
        plural: "-",
        meaning: "Garbage",
        english_sentence: "What do you have to do with the garbage?",
        german_sentence: "Was muss man mit dem Müll machen?",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Der",
        wort: "Abfall",
        plural: "Abfälle",
        meaning: "Garbage",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    { 
        artikel: "Die",
        wort: "Mülltonn",
        plural: "Mülltonne",
        meaning: "Trash can",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Das",
        wort: "Feuer",
        plural: "Feuer",
        meaning: "Fire",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Die",
        wort: "Feuerwehr",
        plural: "Feuerwehren",
        meaning: "Firefighter",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Der",
        wort: "Kinderwagen",
        plural: "Kinderwagen",
        meaning: "Baby carriage",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Der",
        wort: "Hausmeister",
        plural: "Hausmeister",
        meaning: "Maintenance man",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "das ",
        wort: "Zeugnis",
        plural: "Zeugnisse",
        meaning: "Transcript",
        english_sentence: "Melly didn't have a transcript, so her mother had to fax it.",
        german_sentence: "Melly hat ein Zeugnis gefehlt, deshalb musste es ihre Mutter faxen.",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Der",
        wort: "Rückweg",
        plural: "Rückwege",
        meaning: "way back, return path",
        english_sentence: "When Vera was in town for the first time, she couldn't find her way back.",
        german_sentence: "Als Vera das erste Mal in der Stadt war, hat sie den Rückweg nicht gefunden.",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Das",
        wort: "Dorf",
        plural: "Dörfer",
        meaning: "village",
        english_sentence: "Not many people live in our village.",
        german_sentence: "In unserem Dorf wohnen nicht viele Leute.",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Das",
        wort: "Dorf",
        plural: "Dörfer",
        meaning: "village",
        english_sentence: "in the village",
        german_sentence: "auf dem Dorf.",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        artikel: "Das",
        wort: "Land",
        plural: "Länder/Lande",
        meaning: "countryside",
        english_sentence: "I like living in the countryside.",
        german_sentence: "Ich lebe gern auf dem Land.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Platz",
        plural: "-",
        meaning: "space, square",
        english_sentence: "We have high ceilings and plenty of space.",
        german_sentence: "Wir haben hohe Räume und viel Platz.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Parkplatz",
        plural: "-",
        meaning: "parking space",
        english_sentence: "Where can I find a parking space surely?",
        german_sentence: "Wo findet man sicher einen Parkplatz?",
        remark: "",
        chapter: "a2-9",
        create_date: "29/05/2022",
        update_date: "29/05/2022",
    },
    {
        artikel: "Der",
        wort: "Stadtrand",
        plural: "Stadtränder",
        meaning: "suburban, ชานเมือง",
        english_sentence: "We like life on the outskirts.",
        german_sentence: "Uns gefällt das Leben am Stadtrand.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Aufzug",
        plural: "Aufzüge",
        meaning: "elevator",
        english_sentence: "in a high-rise building with an elevator, you don't have to use the stairs.",
        german_sentence: "In einem Hochhaus mit Aufzug muss man nicht die Treppen benutzen.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Strom",
        plural: "-",
        meaning: "electricity",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Eingang",
        plural: "Eingänge",
        meaning: "entrance",
        english_sentence: "There are only a few spaces left at the West Entrance.",
        german_sentence: "Am Eingang West sind nur noch wenige Plätze frei.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Die",
        wort: "Maus",
        plural: "Mäuse",
        meaning: "Mouse",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Die",
        wort: "Katze",
        plural: "Katzen",
        meaning: "Cat",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Die",
        wort: "Kuh",
        plural: "Kühe",
        meaning: "cow",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Das",
        wort: "Küken",
        plural: "Küken",
        meaning: "chick",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Die",
        wort: "Schildkröte",
        plural: "Schildkröten",
        meaning: "Turtle",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Vogel",
        plural: "Vögel",
        meaning: "Bird",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Die",
        wort: "Ente",
        plural: "Enten",
        meaning: "Duck",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Fisch",
        plural: "Fische",
        meaning: "Fish",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Hund",
        plural: "Hunde",
        meaning: "Dog",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Der",
        wort: "Schwan",
        plural: "Schwäne",
        meaning: "swan",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Das",
        wort: "Schwein",
        plural: "Schweine",
        meaning: "pig",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Das",
        wort: "Eichhörnchen",
        plural: "Eichhörnchen",
        meaning: "Squirrel",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "Das",
        wort: "Meerschweinchen",
        plural: "Meerschweinchen",
        meaning: "Guinea pig",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        artikel: "der",
        wort: "Imbiss",
        plural: "Imbisse",
        meaning: "Fast-food restaurant",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "die",
        wort: "Selbstbedienung",
        plural: "Selbstbedienungen",
        meaning: "self-service",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "die",
        wort: "Currywurst",
        plural: "Currywürste",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "der",
        wort: "Schinken",
        plural: "Schinken",
        meaning: "ham",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "der",
        wort: "Apfelsaft",
        plural: "Apfelsäfte",
        meaning: "apple juice",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "das",
        wort: "Brötchen",
        plural: "Brötchen",
        meaning: "Bread roll (small)",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "das",
        wort: "Brot",
        plural: "Brote",
        meaning: "bread (big)",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "die",
        wort: "Stunde",
        plural: "Stunden",
        meaning: "hour",
        english_sentence: "I’ve been waiting at the bus stop for half an hour.",
        german_sentence: "Ich warte schon eine halbe Stunde an der Bushaltestelle.",
        remark: "",
        chapter: "a2-1",
        create_date: "23/05/2022",
        update_date: "23/05/2022",
    },
    {
        artikel: "die",
        wort: "Stunde",
        plural: "Stunden",
        meaning: "hour",
        english_sentence: "He still has 6 hours to study at home.",
        german_sentence: "Zu Hause muss er noch 6 Stunden lernen.",
        remark: "",
        chapter: "a2-1",
        create_date: "05/06/2022",
        update_date: "05/06/2022",
    },
    {
        artikel: "der",
        wort: "Übersetzer",
        plural: "Übersetzer",
        meaning: "translator",
        english_sentence: "Stefan Fischer used to be a translator for German and English.",
        german_sentence: "Stefan Fischer war früher Übersetzer für Deutsch und Englisch.",
        remark: "",
        chapter: "",
        create_date: "26/05/2022",
        update_date: "26/05/2022",
    },
    {
        artikel: "der",
        wort: "Stau",
        plural: "Staus",
        meaning: "Traffic jams",
        english_sentence: "stuck in Traffic",
        german_sentence: "Im Stau stehen",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        artikel: "der",
        wort: "Urlaub",
        plural: "Urlaube",
        meaning: "Holiday",
        english_sentence: "go on vacation",
        german_sentence: "in den Urlaub fahren ",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        artikel: "der",
        wort: "Urlaub",
        plural: "Urlaube",
        meaning: "Holiday",
        english_sentence: "do on vacation",
        german_sentence: "im Urlaub machen",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        artikel: "das",
        wort: "Gewitter",
        plural: "Gewitter",
        meaning: "thunderstorm, พายุฝนฟ้าคะนอง",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "",
        create_date: "29/05/2022",
        update_date: "29/05/2022",
    },
    {
        artikel: "der",
        wort: "Reiseführer",
        plural: "Reiseführer",
        meaning: "tour guide, guidebook,",
        english_sentence: "",
        german_sentence: "",
        remark: "a1-1",
        chapter: "a1-1",
        create_date: "29/05/2022",
        update_date: "29/05/2022",
    },
    {
        artikel: "Die",
        wort: "Reisegruppe",
        plural: "Reisegruppen",
        meaning: "Tour group",
        english_sentence: "What does the tour group do when?",
        german_sentence: "Was macht die Reisegruppe wann?",
        remark: "",
        chapter: "",
        create_date: "31/05/2022",
        update_date: "31/05/2022",
    },
    {
        artikel: "die",
        wort: "Mitte",
        plural: "Mitten",
        meaning: "center, middle",
        english_sentence: "They sit in the front center.",
        german_sentence: "Sie sitzen vorne in der Mitte.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Schwiegereltern",
        plural: "Schwiegereltern",
        meaning: "die Eltern von Ehemann oder Ehefrau",
        english_sentence: "I took the photo during a family party at my parents-in-law’s house.",
        german_sentence: "Das Foto habe ich während eines Famileinfests im Haus meiner Schwiegereltern gemacht.",
        remark: "No singular",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Schwiegereltern",
        plural: "Schwiegereltern",
        meaning: "die Eltern von Ehemann oder Ehefrau",
        english_sentence: "My husband's parents are my parents-in-law’s.",
        german_sentence: "Die Eltern meines Mannes sind meine Schwiegereltern.",
        remark: "No singular",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "der",
        wort: "Schwiegervater",
        plural: "Schwiegerväter",
        meaning: "father-in-law, พ่อตา",
        english_sentence: "In the front far left is my father-in-law's brother and in the front far right is his wife.",
        german_sentence: "Vorne ganz links ist der Bruder meines Schwiegervaters und vorne ganze rechts sitzt seine Frau.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Schwiegermutter",
        plural: "Schwiegermütter",
        meaning: "mother-in-law, แม่สะใภ้",
        english_sentence: "Two siblings of my mother-in-law are sitting in the back next to my sister.",
        german_sentence: "Hinten sitzen neben meiner Schwester zwei Geschwister meiner Schwiegermutter.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "der",
        wort: "Ehemann",
        plural: "Ehemänner",
        meaning: "husband",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Ehefrau",
        plural: "Ehefrauen",
        meaning: "wife",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Geschwister",
        plural: "Geschwister",
        meaning: "zwei oder mehrere Personen, die Brüder und/oder Schwestern sind",
        english_sentence: "If you don't have siblings, you're an only child.",
        german_sentence: "Wenn man keine Geschwister hat, ist man ein Einzelkind.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Schwester",
        plural: "Schwestern",
        meaning: "",
        english_sentence: "My father's daughter is my sister.",
        german_sentence: "Die Tochter meines Vaters ist meine Schwester.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Einzelkind",
        plural: "Einzelkinder",
        meaning: "only child.",
        english_sentence: "If you don't have siblings, you're an only child.",
        german_sentence: "Wenn man keine Geschwister hat, ist man ein Einzelkind.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Generation",
        plural: "Generationen",
        meaning: "generation",
        english_sentence: "If several generations live under one roof, it is an extended family.",
        german_sentence: "Wenn mehrere Generationen unter einem Dach leben, ist es eine Großfamilie.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Großfamilie",
        plural: "Großfamilien",
        meaning: "extended family",
        english_sentence: "If several generations live under one roof, it is an extended family.",
        german_sentence: "Wenn mehrere Generationen unter einem Dach leben, ist es eine Großfamilie.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "das",
        wort: "Familienmodell",
        plural: "Familienmodelle",
        meaning: "",
        english_sentence: "There are many family models, such as the patchwork family or couples without children.",
        german_sentence: "Es gibt viele Familienmodelle, wie zum Beispiel die Patchworkfamilie oder Paare ohne Kinder.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Patchworkfamilie",
        plural: "Patchworkfamilien",
        meaning: "Patchwork family",
        english_sentence: "There are many family models, such as the patchwork family or couples without children.",
        german_sentence: "Es gibt viele Familienmodelle, wie zum Beispiel die Patchworkfamilie oder Paare ohne Kinder.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Erziehung",
        plural: "-",
        meaning: "upbringing, education, raising",
        english_sentence: "Differences of opinion can often arise in the process of raising children",
        german_sentence: "Bei der Erziehung der Kinder kann es oft zu Meinungsverschiedenheiten kommen.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Meinungsverschiedenheit",
        plural: "Meinungsverschiedenheiten",
        meaning: "",
        english_sentence: "Differences of opinion can often arise in the process of raising children",
        german_sentence: "Bei der Erziehung der Kinder kann es oft zu Meinungsverschiedenheiten kommen.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Verschiedenheit",
        plural: "Verschiedenheiten",
        meaning: "difference",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Meinung",
        plural: "Meinungen",
        meaning: "opinion",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Streit",
        plural: "Streite",
        meaning: "argument",
        english_sentence: "Sometimes the opinions in a family are different, and then there can be arguments.",
        german_sentence: "Manchmal sind die Meinungen in einer Familie verschieden. Dann kann es auch Streit geben.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Hausputz",
        plural: "Hausputze",
        meaning: "house-cleaning",
        english_sentence: "We have a house cleaning plan. So everyone takes on their duties.",
        german_sentence: "Wir haben einen Plan für den Hausputz. So übernehmen alle ihre Pflichten.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Pflicht",
        plural: "Pflichten",
        meaning: "duty",
        english_sentence: "We have a house cleaning plan. So everyone takes on their duties.",
        german_sentence: "Wir haben einen Plan für den Hausputz. So übernehmen alle ihre Pflichten.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "adj",
        wort: "alleinerziehend",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "Ich bin geschieden und lebe mit meinem Sohn allein. Ich bin alleinerziehend.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "adj",
        wort: "erschöpft",
        plural: "",
        meaning: "exhaust",
        english_sentence: "I am exhausted.",
        german_sentence: "Ich bin erschöpft.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Husten",
        plural: "Husten",
        meaning: "cough",
        english_sentence: "I have a cough and runny nose. I have a cold.",
        german_sentence: "Ich habe Husten und Schnupfen. Ich habe eine Erkältung.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Schnupfen",
        plural: "Schnupfen",
        meaning: "runny nose",
        english_sentence: "I have a cough and runny nose. I have a cold.",
        german_sentence: "Ich habe Husten und Schnupfen. Ich habe eine Erkältung.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Erkältung",
        plural: "Erkältungen",
        meaning: "cold",
        english_sentence: "I have a cough and runny nose. I have a cold.",
        german_sentence: "Ich habe Husten und Schnupfen. Ich habe eine Erkältung.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Betreuung",
        plural: "-",
        meaning: "care, maintenance",
        english_sentence: "",
        german_sentence: "",
        remark: "no plural",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Möglichkeit",
        plural: "Möglichkeiten",
        meaning: "option, possibility, facility,",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Betreuungsmöglichkeit",
        plural: "Betreuungsmöglichkeiten",
        meaning: "Childcare facilities",
        english_sentence: "Childcare facilities for children are better today than they used to be.",
        german_sentence: "Die Betreuungsmöglichkeiten für Kinder sind heute besser als früher.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "das",
        wort: "Ehepaar",
        plural: "Ehepaare",
        meaning: "married couple",
        english_sentence: "The couple has been married for 30 years.",
        german_sentence: "Das Ehepaar ist seit 30 Jahren verheiratet.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "adj",
        wort: "möglich",
        plural: "",
        meaning: "possible",
        english_sentence: "Full-time employment is often difficult for women with small children.",
        german_sentence: "Für Frauen mit kleinen Kindern ist eine Erwerbstätigkeit in Vollzeit oft nur schwer möglich.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Erwerbstätigkeit",
        plural: "Erwerbstätigkeiten",
        meaning: "employment",
        english_sentence: "Full-time employment is often difficult for women with small children.",
        german_sentence: "Für Frauen mit kleinen Kindern ist eine Erwerbstätigkeit in Vollzeit oft nur schwer möglich.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Vollzeit",
        plural: "-",
        meaning: "full time",
        english_sentence: "Full-time employment is often difficult for women with small children.",
        german_sentence: "Für Frauen mit kleinen Kindern ist eine Erwerbstätigkeit in Vollzeit oft nur schwer möglich.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Teilzeit",
        plural: "-",
        meaning: "Part time job",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "das",
        wort: "Mutterschutzgesetz",
        plural: "Mutterschutzgesetze",
        meaning: "",
        english_sentence: "Are there countries that don't have a maternity protection law?",
        german_sentence: "Gibt es Länder, die kein Mutterschutzgesetz haben?",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Freundeskreis",
        plural: "Freundeskreise",
        meaning: "a circle of friends.",
        english_sentence: "I have a large circle of friends.",
        german_sentence: "Ich habe einen großen Freundeskreis.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Wohnsituation",
        plural: "Wohnsituationen",
        meaning: "housing situation",
        english_sentence: "Many people are not satisfied with their housing situation.",
        german_sentence: "Viele Leute sind mit ihrer Wohnsituation nicht zufrieden.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "adj",
        wort: "zufrieden",
        plural: "",
        meaning: "satisfied",
        english_sentence: "Many people are not satisfied with their housing situation.",
        german_sentence: "Viele Leute sind mit ihrer Wohnsituation nicht zufrieden.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Cousine",
        plural: "Cousinen",
        meaning: "Cousin",
        english_sentence: "My uncle's daughter is my cousin.",
        german_sentence: "Die Tochter meines Onkels ist meine Cousine.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Schwägerin",
        plural: "Schwägerinnen",
        meaning: "sister-in-law",
        english_sentence: "My wife's sister is my sister-in-law.",
        german_sentence: "Die Schwester meiner Ehefrau ist meine Schwägerin.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Chance",
        plural: "Chancen",
        meaning: "chance",
        english_sentence: "Men and women should have equal opportunities at work.",
        german_sentence: "Im Beruf sollen Männer und Frauen die gleichen Chancen haben.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Rolle",
        plural: "Rollen",
        meaning: "roll",
        english_sentence: "In the past, the classic role of women was that they did the household alone.",
        german_sentence: "Früher war die klassische Rolle der Frau, dass sie den Haushalt allein gemacht hat.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Haushalt",
        plural: "Haushalte",
        meaning: "housekeeping",
        english_sentence: "In the past, the classic role of women was that they did the household alone.",
        german_sentence: "Früher war die klassische Rolle der Frau, dass sie den Haushalt allein gemacht hat.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "die",
        wort: "Gleichberechtigung",
        plural: "-",
        meaning: "equal rights",
        english_sentence: "The Basic Law states that women and men have equal rights.",
        german_sentence: "Im Grundgesetz steht, dass Frauen und Männer gleichberechtigt sind.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Familienstand",
        plural: "-",
        meaning: "marital status",
        english_sentence: "I am not married and not divorced. My marital status is single.",
        german_sentence: "Ich bin nicht verheiratet und nicht geschieden. Mein Familienstand ist ledig.",
        remark: "no plural",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "verb",
        wort: "unterstützen",
        plural: "",
        meaning: "",
        english_sentence: "Everyone in the family should help and support each other.",
        german_sentence: "Alle in der Familie sollten sich helfen und unterstützen.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "das",
        wort: "Verhältnis",
        plural: "Verhältnisse",
        meaning: "relationship",
        english_sentence: "I call my mother every day. I have a very close relationship with her.",
        german_sentence: "Ich rufe meine Mutter täglich an. Ich habe ein sehr enges Verhältnis zu ihr.",
        remark: "",
        chapter: "b1-1",
        create_date: "02/07/2022",
        update_date: "02/07/2022",
    },
    {
        artikel: "der",
        wort: "Friseur",
        plural: "Friseure",
        meaning: "barber",
        english_sentence: "I go to the hairdresser and to the supermarket.",
        german_sentence: "Ich gehe zum Friseur und in den Supermarkt.",
        remark: "Pfizer",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "der",
        wort: "Supermarkt",
        plural: "Supermärkte",
        meaning: "supermarket",
        english_sentence: "I go to the hairdresser and to the supermarket.",
        german_sentence: "Ich gehe zum Friseur und in den Supermarkt.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "die",
        wort: "Zeitung",
        plural: "Zeitungen",
        meaning: "newspaper",
        english_sentence: "Where is the newspaper?",
        german_sentence: "Wo ist die Zeitung?",
        remark: "Vielleicht liegt sie auf dem Tisch unter den Büchern.",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Geschenk",
        plural: "Geschenke",
        meaning: "gift, present",
        english_sentence: "I bought a present for my brother.",
        german_sentence: "Ich habe ein Geschenk für meinen Bruder gekauft.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Geschenk",
        plural: "Geschenke",
        meaning: "gift, present",
        english_sentence: "I bought a present for my brother.",
        german_sentence: "Ich habe ein Geschenk für meinen Bruder gekauft.",
        remark: "",
        chapter: "b1-1",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "der",
        wort: "Strand",
        plural: "Strände",
        meaning: "beach",
        english_sentence: "There is a beach nearby.",
        german_sentence: "Es gibt einen Strand in der Nähe.",
        remark: "",
        chapter: "-",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "der",
        wort: "Balkon",
        plural: "Balkons/Balkone",
        meaning: "balcony",
        english_sentence: "Why doesn't the room have a balcony?",
        german_sentence: "Warum hat das Zimmer keinen Balkon?",
        remark: "",
        chapter: "-",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Einzelzimmer",
        plural: "Einzelzimmer",
        meaning: "one-bed room",
        english_sentence: "Do you still have a one-bed room available?",
        german_sentence: "Haben Sie noch ein Einzelzimmer frei?",
        remark: "",
        chapter: "-",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Doppelzimmer",
        plural: "Doppelzimmer",
        meaning: "double bedroom",
        english_sentence: "Do you still have a double room available?",
        german_sentence: "Haben Sie noch ein Doppelzimmer frei?",
        remark: "",
        chapter: "-",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "das",
        wort: "Fenster",
        plural: "Fenster",
        meaning: "window",
        english_sentence: "The room unfortunately doesn't have a window.",
        german_sentence: "Das Zimmer hat leider kein Fenster.",
        remark: "",
        chapter: "-",
        create_date: "01/07/2022",
        update_date: "01/07/2022",
    },
    {
        artikel: "adj",
        wort: "anderes",
        plural: "",
        meaning: "",
        english_sentence: "Another word for screen is monitor / display.",
        german_sentence: "Ein anderes Wort für Bildschirm ist Monitor/Display.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Bildschirm",
        plural: "Bildschirme",
        meaning: "display screen",
        english_sentence: "Another word for screen is monitor / display.",
        german_sentence: "Ein anderes Wort für Bildschirm ist Monitor/Display.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Monitor",
        plural: "Monitore",
        meaning: "monitor",
        english_sentence: "Another word for screen is monitor / display.",
        german_sentence: "Ein anderes Wort für Bildschirm ist Monitor/Display.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "das",
        wort: "Display",
        plural: "Displays",
        meaning: "display",
        english_sentence: "Another word for screen is monitor / display.",
        german_sentence: "Ein anderes Wort für Bildschirm ist Monitor/Display.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Drucker",
        plural: "Drucker",
        meaning: "printer",
        english_sentence: "A device with which man can print documents, the printer.",
        german_sentence: "Ein Gerät, mit dem Mann Dokumente drucken kann, der Drucker.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "das",
        wort: "Gerät",
        plural: "Geräte",
        meaning: "device",
        english_sentence: "A device with which man can print documents, the printer.",
        german_sentence: "Ein Gerät, mit dem Mann Dokumente drucken kann, der Drucker.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "drucken",
        plural: "",
        meaning: "print",
        english_sentence: "A device with which man can print documents, the printer.",
        german_sentence: "Ein Gerät, mit dem Mann Dokumente drucken kann, der Drucker.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "das",
        wort: "Dokument",
        plural: "Dokumente",
        meaning: "document",
        english_sentence: "A device with which man can print documents, the printer.",
        german_sentence: "Ein Gerät, mit dem Mann Dokumente drucken kann, der Drucker.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "das",
        wort: "Medium",
        plural: "Medien",
        meaning: "communication medium",
        english_sentence: "A computer, a tablet, a smartphone are digital media.",
        german_sentence: "Ein Computer, ein Tablet, ein Smartphone sind digitale Medien.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "adj",
        wort: "digital",
        plural: "",
        meaning: "digital",
        english_sentence: "A computer, a tablet, a smartphone are digital media.",
        german_sentence: "Ein Computer, ein Tablet, ein Smartphone sind digitale Medien.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Mensch",
        plural: "Menschen",
        meaning: "person, human being",
        english_sentence: "How many people in Germany use the Internet?",
        german_sentence: "Wie viele Menschen in Deutschland nutzen das Internet?",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "nutzen",
        plural: "",
        meaning: "",
        english_sentence: "How many people in Germany use the Internet?",
        german_sentence: "Wie viele Menschen in Deutschland nutzen das Internet?",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "adj",
        wort: "geschäftlich",
        plural: "",
        meaning: "",
        english_sentence: "I almost never use my smartphone privately, but mostly for work / business.",
        german_sentence: "Ich nutze mein Smartphone fast nie privat, sondern meistens beruflich / geschäftlich.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "adj",
        wort: "beruflich",
        plural: "",
        meaning: "",
        english_sentence: "I almost never use my smartphone privately, but mostly for work / business.",
        german_sentence: "Ich nutze mein Smartphone fast nie privat, sondern meistens beruflich / geschäftlich.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "adj",
        wort: "erreichbar",
        plural: "",
        meaning: "achievable, attainable, reachable, accessible",
        english_sentence: "Sorry, Mr Brunner is not available at the moment.",
        german_sentence: "Tut mir leid, Herr Brunner ist im Moment nicht erreichbar.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "sich austauschen",
        plural: "exchange",
        meaning: "",
        english_sentence: "I exchange information with friends every day via the Internet.",
        german_sentence: "Ich tausche mich täglich über das Internet mit Freunden aus.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "knüpfen",
        plural: "",
        meaning: "to form , to establish",
        english_sentence: "On the Internet you can get to know people and make contacts.",
        german_sentence: "Im Internet kann man Leute kennenlernen und Kontakte knüpfen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "verbringen",
        plural: "",
        meaning: "to spend",
        english_sentence: "I spend two hours a day online.",
        german_sentence: "Ich verbringe täglich zwei Stunden im Netz.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "teilnehmen",
        plural: "",
        meaning: "participate",
        english_sentence: "I would like to participate in an e-learning course.",
        german_sentence: "Ich würde gerne an einem E-Learning-Kurs teilnehmen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "umgehen",
        plural: "",
        meaning: "handle, interact",
        english_sentence: "Many small children are good with the computer.",
        german_sentence: "Viele kleine Kinder können gut mit dem Computer umgehen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "herunterzuladen",
        plural: "",
        meaning: "download",
        english_sentence: "Finn’s been trying to download an app for hours.",
        german_sentence: "Finn versucht seit Stunden, eine App herunterzuladen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "versucht",
        plural: "",
        meaning: "try",
        english_sentence: "Finn’s been trying to download an app for hours.",
        german_sentence: "Finn versucht seit Stunden, eine App herunterzuladen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "chatten",
        plural: "",
        meaning: "",
        english_sentence: "It’s fun to chat with friends.",
        german_sentence: "Es macht Spaß, mit Freunden zu chatten.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "ausschalten",
        plural: "",
        meaning: "turn off",
        english_sentence: "Students have to turn off their cell phones in class.",
        german_sentence: "Schüler müssen ihre Handys im Unterricht ausschalten.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Vorteil",
        plural: "Vorteile",
        meaning: "advantage",
        english_sentence: "One advantage is that online shopping is very convenient.",
        german_sentence: "Ein Vorteil ist, dass Online-Shopping sehr bequem ist.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Nachteil",
        plural: "Nachteile",
        meaning: "",
        english_sentence: "A disadvantage is that you can not try on the clothes.",
        german_sentence: "Ein Nachteil ist, dass man die Kleider nicht nicht anprobieren kann.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "eingeben",
        plural: "",
        meaning: "enter, input",
        english_sentence: "First you have to enter the password. Then you have to confirm it.",
        german_sentence: "Zuerst müssen Sie das Passwort eingeben. Dann müssen Sie es bestätigen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "bestätigen",
        plural: "",
        meaning: "confirm",
        english_sentence: "First you have to enter the password. Then you have to confirm it.",
        german_sentence: "Zuerst müssen Sie das Passwort eingeben. Dann müssen Sie es bestätigen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "zustimmen",
        plural: "",
        meaning: "agree to",
        english_sentence: "Please agree to the terms and conditions.",
        german_sentence: "Bitte stimmen Sie den AGB zu.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "die",
        wort: "Zahlungsmethode",
        plural: "Zahlungsmethoden",
        meaning: "method",
        english_sentence: "If you would like to pay by credit card or invoice, please select the payment method.",
        german_sentence: "Möchten Sie mit Kreditkarte oder auf Rechnung bezahlen. Wählen Sie bitte die Zahlungsmethode.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "adj",
        wort: "süchtig",
        plural: "",
        meaning: "hooked, addicted",
        english_sentence: "Many parents are afraid that smartphones will make their children addicted.",
        german_sentence: "Viele Eltern haben Angst, dass Smartphones ihre Kinder süchtig machen.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Warenkorb",
        plural: "Warenkörbe",
        meaning: "market basket",
        english_sentence: "I want to buy something online and add the product to the shopping cart.",
        german_sentence: "Ich möchte online etwas kaufen und füge das Produkt zum Warenkorb hinzu.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "das",
        wort: "Rückgaberecht",
        plural: "",
        meaning: "refund policy",
        english_sentence: "If I do not like a product, I have 14 days return policy.",
        german_sentence: "Wenn mir ein Produkt nicht gefällt, haben ich 14 Tage Rückgaberecht.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "prüfen",
        plural: "",
        meaning: "check, exammine",
        english_sentence: "Please check your order = Please check your order.",
        german_sentence: "Bitte kontrollieren Sie Ihre Bestellung. = Bitte prüfen Sie Ihre Bestellung.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "Ich habe schon schlechte Erfahrungen beim Internet-Einkauf gemacht.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "verb",
        wort: "bewerten",
        plural: "",
        meaning: "rate, review",
        english_sentence: "How did you like your stay with us? Please rate our hotel",
        german_sentence: "Wie hat Ihnen Ihr Aufenthalt bei uns gefallen? Bitte bewerten Sie unser Hotel.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "",
        wort: "unterwegs",
        plural: "",
        meaning: "",
        english_sentence: "I study on the computer at home, or on the go on my tablet.",
        german_sentence: "Ich lerne am Computer zu Hause, oder unterwegs am Tablet.",
        remark: "",
        chapter: "b1-2",
        create_date: "05/07/2022",
        update_date: "05/07/2022",
    },
    {
        artikel: "der",
        wort: "Geschäftsführer",
        plural: "Geschäftsführer",
        meaning: "CEO, director, manager",
        english_sentence: "He doesn't earn badly because he's a department head. Above him is only the managing director.",
        german_sentence: "Er verdient nicht schlecht, denn er ist Abteilungsleiter. Über ihm ist nur noch der Geschäftsführer.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "der",
        wort: "Abteilungsleiter",
        plural: "Abteilungsleiter",
        meaning: "department manager",
        english_sentence: "He doesn't earn badly because he's a department head. Above him is only the managing director.",
        german_sentence: "Er verdient nicht schlecht, denn er ist Abteilungsleiter. Über ihm ist nur noch der Geschäftsführer.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "der",
        wort: "Maschinenbauingenieur",
        plural: "Maschinenbauingenieure",
        meaning: "mechanical engineer",
        english_sentence: "A mechanical engineer needs a degree.",
        german_sentence: "Ein Maschinenbauingenieur braucht ein Studium.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "das",
        wort: "Studium",
        plural: "Studien",
        meaning: "academic studies, degree",
        english_sentence: "A mechanical engineer needs a degree.",
        german_sentence: "Ein Maschinenbauingenieur braucht ein Studium.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "der",
        wort: "Auszubildender",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "das",
        wort: "Unternehmen",
        plural: "Unternehmen",
        meaning: "company",
        english_sentence: "Heriton is a very old company.",
        german_sentence: "Heriton ist ein sehr altes Unternehmen.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "das",
        wort: "Produkt",
        plural: "Produkte",
        meaning: "Product",
        english_sentence: "The products have an excellent reputation.",
        german_sentence: "Die Produkte haben einen ausgezeichneten Ruf.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "der",
        wort: "Ruf",
        plural: "Rufe",
        meaning: "reputation",
        english_sentence: "The products have an excellent reputation.",
        german_sentence: "Die Produkte haben einen ausgezeichneten Ruf.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "adj",
        wort: "ausgezeichnet",
        plural: "",
        meaning: "excellent",
        english_sentence: "The products have an excellent reputation.",
        german_sentence: "Die Produkte haben einen ausgezeichneten Ruf.",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "das",
        wort: "Paar",
        plural: "Paare",
        meaning: "couple, pair",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
    {
        artikel: "",
        wort: "",
        plural: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "12/07/2022",
        update_date: "12/07/2022",
    },
]




module.exports = {
    adjektiv: adjektiv,
}