const adjektiv = [
    {
        adjektiv: "verärgert",
        meaning: "annoy, upset",
        english_sentence: "The boss thinks that her employees do a bad job. That's why she's upset.",
        german_sentence: "Die Chefin findet, dass ihre Mitarbeiter schlecht arbeiten. Deshalb ist sie verärgert.",
        remark: "https://quizlet.com/695528147/flashcards",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "hilfsbereit",
        meaning: "helpful",
        english_sentence: "My colleagues often help me. They are very helpful.",
        german_sentence: "Meine Kollegen helfen mir oft. Sie sind sehr hilfsbereit.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "nervös",
        meaning: "nervous",
        english_sentence: "Before a job interview, many people are very nervous.",
        german_sentence: "Vor einem Bewerbungsgespräch sind viele Leute sehr nervös.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "streng",
        meaning: "strict",
        english_sentence: "Our teacher at the vocational school is nice but strict.",
        german_sentence: "Unsere Lehrerin in der Berufsschule ist nett, aber streng.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "elegant",
        meaning: "elegant",
        english_sentence: "Mr. Jankowski always wears clothes that are very elegant.",
        german_sentence: "Herr Jankowski trägt immer Kleidung, die sehr elegant ist.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "gepflegt",
        meaning: "neat, trim, well-groomed",
        english_sentence: "My daughter is very careful about her appearance and hygiene. She is very well cared for.",
        german_sentence: "Meine Tochter achtet sehr auf ihr Aussehen und ihre Hygiene. Sie ist sehr gepflegt.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "unangemessen",
        meaning: "inappropriate",
        english_sentence: "Coming to an interview in shorts is inappropriate.",
        german_sentence: "Zu einem Bewerbungsgespräch in Shorts zu kommen, ist unangemessen.",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "zufrieden",
        meaning: "satisfied",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "fleißig",
        meaning: "hard-working",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "ehrgeizig",
        meaning: "ambitious",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "aufmerksam",
        meaning: "attentive",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "unaufmerksam",
        meaning: "inattentive",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "ungeduldig",
        meaning: "impatient",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "sympathisch",
        meaning: "friendly",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "schlecht gelaunt",
        meaning: "in a bad mood",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "freundlich",
        meaning: "friendly",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "entspannt",
        meaning: "relaxed",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "gelangweilt",
        meaning: "bored",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "ruhig",
        meaning: "calm",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "genervt",
        meaning: "annoyed",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "höflich",
        meaning: "polite",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "interessiert",
        meaning: "Interested",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "desinteressiert",
        meaning: "disinterested",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
    {
        adjektiv: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "b1-3",
        create_date: "13/07/2022",
        update_date: "13/07/2022",
    },
]




module.exports = {
    adjektiv: adjektiv,
}