const comparative_adj = [
    { 
        adjektive: "viel",
        komparativ: "mehr",
        superlativ: "am meisten",
        meaning: "a lot",
        english_sentence: "I almost never see most people.",
        german_sentence: "Die meisten Leute sehe ich fast nie.",
        remark: "",
        chapter: "a2-8",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    {
        adjektive: "schnell",
        komparativ: "schneller",
        superlativ: "am schnellsten",
        meaning: "fast",
        english_sentence: "Which means of transport is the fastest?",
        german_sentence: "Welches Verkehrsmittel ist am schnellsten?",
        remark: "",
        chapter: "a2-8",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "eng",
        komparativ: "enger",
        superlativ: "am engsten",
        meaning: "narrow",
        english_sentence: "Which streets in Bangkok are quite narrow?",
        german_sentence: "Welche Straße in Bangkok sind ziemlich eng?",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "breit",
        komparativ: "breiter",
        superlativ: "am breitesten",
        meaning: "Wide",
        english_sentence: "Is the road narrow or wide?",
        german_sentence: "Ist die Straße eng oder breit?",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "problematisch",
        komparativ: "problematischer",
        superlativ: "am problematischsten",
        meaning: "problematic",
        english_sentence: "This is of course problematic.",
        german_sentence: "Das ist natürlich problematisch.",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "schmutzig",
        komparativ: "schmutziger",
        superlativ: "am schmutzigsten",
        meaning: "dirty",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "sauber",
        komparativ: "sauberer",
        superlativ: "am saubersten",
        meaning: "clean",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "nass",
        komparativ: "nasser/nässer",
        superlativ: "am nassesten/nässesten",
        meaning: "wet",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "trocken",
        komparativ: "trockener",
        superlativ: "am trockensten",
        meaning: "dry",
        english_sentence: "-",
        german_sentence: "-",
        remark: "",
        chapter: "a2-9",
        create_date: "11/05/2022",
        update_date: "11/05/2022",
    },
    {
        adjektive: "entfernt",
        komparativ: "entfernter",
        superlativ: "am entferntesten",
        meaning: "distant",
        english_sentence: "6 km from the village",
        german_sentence: "6 km vom Dorf entfernt",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        adjektive: "unbedingt",
        komparativ: "-",
        superlativ: "-",
        meaning: "absolute, by all means, at all events, unconditional",
        english_sentence: "You absolutely have to see the movie with him, that's in theaters right now.",
        german_sentence: "Du musst unbedingt den Film mit ihm sehen, der gerade in den Kinos läuft.",
        remark: "",
        chapter: "a2-10",
        create_date: "13/05/2022",
        update_date: "13/05/2022",
    },
    {
        adjektive: "los",
        komparativ: "loser",
        superlativ: "am losesten",
        meaning: "loose",
        english_sentence: "What's going on here?",
        german_sentence: "Was ist hier los?",
        remark: "",
        chapter: "a2-10",
        create_date: "17/05/2022",
        update_date: "17/05/2022",
    },
    {
        adjektive: "",
        komparativ: "",
        superlativ: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-10",
        create_date: "13/05/2022",
        update_date: "13/05/2022",
    },
    {
        adjektive: "",
        komparativ: "",
        superlativ: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-10",
        create_date: "13/05/2022",
        update_date: "13/05/2022",
    },
    {
        adjektive: "",
        komparativ: "",
        superlativ: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-10",
        create_date: "13/05/2022",
        update_date: "13/05/2022",
    },
    {
        adjektive: "",
        komparativ: "",
        superlativ: "",
        meaning: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "a2-10",
        create_date: "13/05/2022",
        update_date: "13/05/2022",
    },
]

module.exports = {
    comparative_adj: comparative_adj,

}