const words = [
    {
        thema: "-",
        english_sentence: "How are you doing?",
        german_sentence: "Wie geht es Ihnen?",
        remark: "",
        chapter: "a1-1",
        create_date: "03/06/2022",
        update_date: "03/06/2022",
    },
    {
        thema: "-",
        english_sentence: "How are you doing?",
        german_sentence: "Wie geht es euch?",
        remark: "",
        chapter: "a1-1",
        create_date: "04/06/2022",
        update_date: "04/06/2022",
    },
    {
        thema: "-",
        english_sentence: "How are you doing?",
        german_sentence: "Wie geht es dir?",
        remark: "",
        chapter: "a1-1",
        create_date: "03/06/2022",
        update_date: "03/06/2022",
    },
    {
        thema: "-",
        english_sentence: "How are you doing?",
        german_sentence: "Wie geht's?",
        remark: "",
        chapter: "a1-1",
        create_date: "03/06/2022",
        update_date: "03/06/2022",
    },
    {
        thema: "-",
        english_sentence: "And you?",
        german_sentence: "Und Ihnen?",
        remark: "",
        chapter: "a1-1",
        create_date: "03/06/2022",
        update_date: "03/06/2022",
    },
    {
        thema: "-",
        english_sentence: "And you?",
        german_sentence: "Und dir?",
        remark: "",
        chapter: "a1-1",
        create_date: "03/06/2022",
        update_date: "03/06/2022",
    },
    {
        thema: "-",
        english_sentence: "Thank you, very well.",
        german_sentence: "Danke, sehr gut.",
        remark: "",
        chapter: "a1-1",
        create_date: "03/06/2022",
        update_date: "03/06/2022",
    },
    {
        thema: "Sie haben keine Lust.",
        english_sentence: "Oh, I do not know.",
        german_sentence: "Ach, ich weiß nicht.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        thema: "-",
        english_sentence: "Um, no, wait a minute",
        german_sentence: "Äh, nee, warte mal",
        remark: "",
        chapter: "",
        create_date: "25/05/2022",
        update_date: "25/05/2022",
    },
    {
        thema: "-",
        english_sentence: "Oh well อืม",
        german_sentence: "Naja",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "Sprechen Test",
        english_sentence: "Now I'm going to talk about the topic ,,...'''",
        german_sentence: "Jetzt spreche ich über das Thema ,,...'''",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "Sprechen Test",
        english_sentence: "Now I present the topic ,,...'''",
        german_sentence: "Jetzt präsentiere ich das Thema ,,...'''",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "",
        english_sentence: "I'm just kidding",
        german_sentence: "Ich mach nur Spaß",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "Do we want to do something together... ?",
        german_sentence: "Wollen wir vielleicht zusammen ... ?",
        remark: "Present",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "I have a good idea. We could...",
        german_sentence: "Ich habe eine gute Idee. Wir könnten ...",
        remark: "Konjunktiv II",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "Can we meet at...? Do you have time there?",
        german_sentence: "Können wir uns um ... treffen? Hast du da Zeit?",
        remark: "Present",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "Can you be at ... at / in ...?",
        german_sentence: "Kannst du um ... bei/in ... sein?",
        remark: "Present",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "Zustimmen(agree)",
        english_sentence: "That's a good idea",
        german_sentence: "Das ist eine gute Idee",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "Zustimmen(agree)",
        english_sentence: "Agreed, I like that a lot.",
        german_sentence: "Einverstanden, das gefällt mir gut.",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "Einen Gegenvorschlag machen",
        english_sentence: "Don't we prefer ... ?",
        german_sentence: "Wollen wir nicht lieber ... ?",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "What's the prize?",
        german_sentence: "Was kann man gewinnen?",
        remark: "Future",
        chapter: "",
        create_date: "29/05/2022",
        update_date: "29/05/2022",
    },
    {
        thema: "",
        english_sentence: "Tell me",
        german_sentence: "Sag mal",
        remark: "",
        chapter: "",
        create_date: "30/05/2022",
        update_date: "30/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
]

const words2 = [
]

module.exports = {
    words: words,
    words2: words2,
}

