const words = [
    {
        thema: "Sie haben keine Lust.",
        english_sentence: "Oh, I do not know.",
        german_sentence: "Ach, ich weiß nicht.",
        remark: "",
        chapter: "a2-9",
        create_date: "12/05/2022",
        update_date: "12/05/2022",
    },
    {
        thema: "-",
        english_sentence: "Um, no, wait a minute",
        german_sentence: "Äh, nee, warte mal",
        remark: "",
        chapter: "",
        create_date: "25/05/2022",
        update_date: "25/05/2022",
    },
    {
        thema: "-",
        english_sentence: "Oh well อืม",
        german_sentence: "Naja",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "Sprechen Test",
        english_sentence: "Now I'm going to talk about the topic ,,...'''",
        german_sentence: "Jetzt spreche ich über das Thema ,,...'''",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "Sprechen Test",
        english_sentence: "Now I present the topic ,,...'''",
        german_sentence: "Jetzt präsentiere ich das Thema ,,...'''",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "",
        english_sentence: "I'm just kidding",
        german_sentence: "Ich mach nur Spaß",
        remark: "",
        chapter: "",
        create_date: "27/05/2022",
        update_date: "27/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "einen vorschlag machen",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
    {
        thema: "",
        english_sentence: "",
        german_sentence: "",
        remark: "",
        chapter: "",
        create_date: "28/05/2022",
        update_date: "28/05/2022",
    },
]

const words2 = [
]

module.exports = {
    words: words,
    words2: words2,
}

