const words = [
    { 
        artikel: "verb", 
        wort: "reparieren",
        plural: "",          
        english_sentence: "They fixed my car very quickly.",                 
        german_sentence: "Die haben da mein Auto auch ganz schnell repariert.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "landen",
        plural: "",          
        english_sentence: "Right away, we’ll land in 15 minutes.",                 
        german_sentence: "Gleich, wir landen in einer Viertelstunde.",
        chapter: "a2-6",       
    },
    { 
        artikel: "verb", 
        wort: "rückwärts fahren",
        plural: "",          
        english_sentence: "But you have to drive backwards and I can’t do that so well.",                 
        german_sentence: "Da muss man aber rückwärts fahren und das kann ich nicht so gut.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "bremsen",
        plural: "",          
        english_sentence: "Well, Suddenly a car came from the right and I could not brake so fast.",                 
        german_sentence: "Na ja, plötzlich ist ein Auto von rechts gekommen und ich konnte nicht so schell bremsen.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "verbringen",
        plural: "",          
        english_sentence: "Mira wants to spend a weekend in Berlin.",                 
        german_sentence: "Mira will ein Wochenende in Berlin verbringen.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "sparen",
        plural: "",          
        english_sentence: "Save money!",                 
        german_sentence: "Sparen Sie Geld!",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "überraschen",
        plural: "",          
        english_sentence: "A friend’s birthday and you want to surprise her.",                 
        german_sentence: "Eine Freundin hat Geburtstag und Sie möchten sie überraschen.",
        chapter: "a2-6",           
    },
    { 
        artikel: "adverb", 
        wort: "draußen",
        plural: "",          
        english_sentence: "She likes to be outside with friends",                 
        german_sentence: "Sie ist gern mit Freunden draußen.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "mieten",
        plural: "",          
        english_sentence: "Rent our bike!",                 
        german_sentence: "Mieten Sie unser bike!",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "lenken",
        plural: "",          
        english_sentence: "A team leader steers and brakes the bike.",                 
        german_sentence: "Ein Teamleiter lenkt und bremst das Rad.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "bremsen",
        plural: "",          
        english_sentence: "A team leader steers and brakes the bike.",                 
        german_sentence: "Ein Teamleiter lenkt und bremst das Rad.",
        chapter: "a2-6",           
    },
    { 
        artikel: "adjective", 
        wort: "mobil",
        plural: "",          
        english_sentence: "You want to be flexible and mobile in the city.",                 
        german_sentence: "Sie möchten in der Stadt flexibel und mobil sein.",
        chapter: "a2-6",           
    },
    { 
        artikel: "adjective", 
        wort: "mobil",
        plural: "",          
        english_sentence: "She also wants to be mobile in Munich.",                 
        german_sentence: "Auch in München will sie mobil sein.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "stehen",
        plural: "",          
        english_sentence: "The Bikes of 'Call a Bike' are ready for you 24 hours a day.",                 
        german_sentence: "Die Rädar von Call a Bike stehen 24 Stunden für Sie bereit.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb", 
        wort: "melden",
        plural: "",
        meaning: "report",
        english_sentence: "When you no longer need the bike, lock it and use your cell phone to get in touch.",                 
        german_sentence: "Wenn Sie das Rad nicht mehr brauchen, schließen Sie es ab und melden sich kurz übers Handy.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb",
        wort: "abschließen",
        plural: "",
        meaning: "lock",    
        english_sentence: "When you no longer need the bike, lock it and use your cell phone to get in touch.",                 
        german_sentence: "Wenn Sie das Rad nicht mehr brauchen, schließen Sie es ab und melden sich kurz übers Handy.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb",
        wort: "losfahren",
        plural: "",
        meaning: "set off",    
        english_sentence: "Now, we're supposed to be on the road before 9.",                 
        german_sentence: "Wir sollen vor 9 Uhr losfahren.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb",
        wort: "losfahren",
        plural: "",
        meaning: "set off",    
        english_sentence: "Register and simply drive off with your customer card.",                 
        german_sentence: "Melden Sie sich an und fahren Sie mit Ihrer Kundenkarte einfach los.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb",
        wort: "anmelden",
        plural: "",
        meaning: "register",    
        english_sentence: "Register and simply drive off with your customer card.",                 
        german_sentence: "Melden Sie sich an und fahren Sie mit Ihrer Kundenkarte einfach los.",
        chapter: "a2-6",           
    },
    { 
        artikel: "verb",
        wort: "unterschreiben",
        plural: "",
        meaning: "sign",    
        english_sentence: "none",                 
        german_sentence: "none",
        chapter: "a2-6",           
        create_date: "04/05/2022"
    },
    { 
        artikel: "verb",
        wort: "pendeln",
        plural: "",
        meaning: "commute",    
        english_sentence: "none",                 
        german_sentence: "none",
        remark: "Subj als Person",
        chapter: "a2-6",           
        create_date: "04/05/2022"
    },
    { 
        artikel: "verb",
        wort: "verpassen",
        plural: "",
        meaning: "miss",    
        english_sentence: "We'll miss the train",                 
        german_sentence: "Wir verpassen den Zug",
        chapter: "a2-6",           
        create_date: "04/05/2022"
    },
    { 
        artikel: "verb",
        wort: "erreichen",
        plural: "",
        meaning: "reach",    
        english_sentence: "We reach the train",                 
        german_sentence: "Wir erreichen den Zug",
        remark: "",
        chapter: "a2-6",           
        create_date: "04/05/2022"
    },
    { 
        artikel: "verb",
        wort: "funktionieren",
        plural: "",
        meaning: "funtion, work",    
        english_sentence: "The navi works",                 
        german_sentence: "Der Navi funktioniert",
        remark: "",
        chapter: "a2-6",           
        create_date: "04/05/2022",
    },
    { 
        artikel: "verb",
        wort: "empfehlen",
        plural: "",
        meaning: "recommend, advise",    
        english_sentence: "I recommend the high ropes course.",                 
        german_sentence: "Ich empfehle euch den Hochseilgarten.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    { 
        artikel: "verb",
        wort: "schicken",
        plural: "",
        meaning: "send",
        english_sentence: "Mrs.Korkmaz sends a letter to a man.",
        german_sentence: "Frau Korkmaz schickt einem Mann einen Brief.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    { 
        artikel: "verb",
        wort: "“schenken“",
        plural: "",
        meaning: "give",
        english_sentence: "Clemens gives her husband a bicycle.",
        german_sentence: "Clemens schenkt ihrem Mann ein Fahrrad.",
        remark: "The word “schenken“ implies that you give something to someone without ever wanting it back. Use “schenken” when talking about presents and gifts. Use “geben” when you want someone to give or pass you something.",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    { 
        artikel: "verb",
        wort: "zeigen",
        plural: "",
        meaning: "present, show",
        english_sentence: "I show the tourists the city.",
        german_sentence: "Ich zeige den Touristen die Stadt.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
]

akku_dativ_verb = [
    {
        nominativ: "Die Profis",
        verb: "erklären",
        dativ: "den Leuten",
        akkusativ: "die Regeln",
        english_sentence: "The pros explain the rules to people.",
        german_sentence: "Die Profis erklären den Leuten die Regeln.",
        remark: "",
        chapter: "a2-8",           
        create_date: "07/05/2022",
    },
    {
        nominativ: "Sie",
        verb: "geben",
        dativ: "den Besuchern",
        akkusativ: "Helme",
        english_sentence: "They give the visitors helmets.",
        german_sentence: "Sie geben den Besuchern Helme.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Conny",
        verb: "leiht",
        dativ: "ihrer Freundin",
        akkusativ: "eine Sporthose",
        english_sentence: "Conny lends her friend a pair of sports pants.",
        german_sentence: "Conny leiht ihrer Freundin eine Sporthose.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Herr Weber",
        verb: "empfiehlt",
        dativ: "seiner Frau",
        akkusativ: "das Restaurant",
        english_sentence: "Mr.Weber recommends the restaurant to his wife.",
        german_sentence: "Herr Weber empfiehlt seiner Frau das Restaurant.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Der Lehrer",
        verb: "erklärt",
        dativ: "den Studenten",
        akkusativ: "die Grammatik",
        english_sentence: "The teacher explains the grammar to the students.",
        german_sentence: "Der Lehrer erklärt den Studenten die Grammatik.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Die Trainerin",
        verb: "gibt",
        dativ: "den Leuten",
        akkusativ: "den Helm",
        english_sentence: "The trainer gives people the helmet.",
        german_sentence: "Die Trainerin gibt den Leuten den Helm.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Frau Korkmaz",
        verb: "schickt",
        dativ: "einem Mann",
        akkusativ: "einen Brief",
        english_sentence: "Mrs.Korkmaz sends a letter to a man.",
        german_sentence: "Frau Korkmaz schickt einem Mann einen Brief.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Das Kind",
        verb: "bringt",
        dativ: "seinen Eltern",
        akkusativ: "einen Kaffee",
        english_sentence: "The child brings his parents a coffee.",
        german_sentence: "Das Kind bringt seinen Eltern einen Kaffee.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Clemens",
        verb: "schenkt",
        dativ: "ihrem Man",
        akkusativ: "ein Fahrrad",
        english_sentence: "Clemens gives her husband a bicycle.",
        german_sentence: "Clemens schenkt ihrem Mann ein Fahrrad.",
        remark: "The word “schenken“ implies that you give something to someone without ever wanting it back. Use “schenken” when talking about presents and gifts. Use “geben” when you want someone to give or pass you something.",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
    {
        nominativ: "Ich",
        verb: "zeige",
        dativ: "den Touristen",
        akkusativ: "die Stadt",
        english_sentence: "I show the tourists the city.",
        german_sentence: "Ich zeige den Touristen die Stadt.",
        remark: "",
        chapter: "a2-8",           
        create_date: "08/05/2022",
    },
]

akku_dativ_example_verb = [
    {
        question: "Was schenkt Tom seinem Kind?",
        answer: "Tom schenkt seinem Kind ein Spielzeug.",
        question2: "Was schenkt Tom seinem Kind?",
        answer2: "Tom schenkt ihm ein Spielzeug.",
        question3: "Wem schenkt Tom ein Spielzeug?",
        answer3: "Tom schenkt es seinem Kind.",
        question4: "Schenkt Tom seinem Kind ein Spielzeug?",
        answer4: "Ja, Tom schenkt es ihm",
    },
    {
        question: "Was schenkt Tom seiner Frau?",
        answer: "Tom schenkt seiner Frau eine Marketasche.",
        question2: "Was schenkt Tom seiner Frau?",
        answer2: "Tom schenkt ihr eine Marketasche.",
        question3: "Wem schenkt Tom eine Marketasche?",
        answer3: "Tom schenkt sie seiner Frau.",
        question4: "Schenkt Tom seiner Frau eine Marketasche?",
        answer4: "Ja, Tom schenkt sie ihr",
    },
    {
        question: "Was schenkt Tom seiner Mutter?",
        answer: "Tom schenkt seiner Mutter einen Schal.",
        question2: "Was schenkt Tom seiner Mutter?",
        answer2: "Tom schenkt ihr einen Schal.",
        question3: "Wem schenkt Tom einen Schal?",
        answer3: "Tom schenkt ihn seiner Mutter.",
        question4: "Schenkt Tom seiner Mutter einen Schal?",
        answer4: "Ja, Tom schenkt ihn ihr. ",
    },
    {
        question: "Was schenkt Tom seinem Bruder?",
        answer: "Tom schenkt seinem Bruder ein Fotobuch.",
        question2: "Was schenkt Tom seinem Bruder?",
        answer2: "Tom schenkt ihm ein Fotobuch.",
        question3: "Wem schenkt Tom eine Fotobuch?",
        answer3: "Tom schenkt es seinem Bruder.",
        question4: "Schenkt Tom seinem Bruder ein Fotobuch?",
        answer4: "Ja, Tom schenkt es ihm.",
    },
    {
        question: "Was schenkt Tom seiner Schwester?",
        answer: "Tom schenkt seiner Schwester einen Schminkspiegel.",
        question2: "Was schenkt Tom seiner Schwester?",
        answer2: "Tom schenkt ihr einen Schminkspiegel.",
        question3: "Wem schenkt Tom einen Schminkspiegel?",
        answer3: "Tom schenkt ihn seiner Schwester.",
        question4: "Schenkt Tom seiner Schwester einen Schminkspiegel?",
        answer4: "Ja, Tom schenkt ihn ihr.",
    },
    {
        question: "Was erklärt Tom seinem Schüler?",
        answer: "Tom erklärt seinem Schüler die Hausaufgaben.",
        question2: "Was erklärt Tom seinem Schüler?",
        answer2: "Tom erklärt ihm die Hausaufgaben.",
        question3: "Wem erklärt Tom die Hausaufgaben?",
        answer3: "Tom erklärt sie seinem Schüler.",
        question4: "Erklärt Tom seinem Schüler die Hausaufgaben?",
        answer4: "Ja, Tom erklärt sie ihm.",
    },
    {
        question: "Was kauft Best ihrem Vater?",
        answer: "Best kauft ihrem Vater ein neues Haus.",
        question2: "Was kauft Best ihrem Vater?",
        answer2: "Best kauft ihm ein neues Hau.",
        question3: "Wem kauft Best ein neues Haus?",
        answer3: "Tom erklärt es ihrem Vater.",
        question4: "Kauf Best ihrem Vater ein neues Haus?",
        answer4: "Ja, Tom erklärt es ihm.",
    },
]
module.exports = {
    words: words,
    akku_dativ_verb: akku_dativ_verb,
    akku_dativ_example_verb: akku_dativ_example_verb,

}