const words = [
    { 
        artikel: "das",
        wort: "Aushilfe",
        plural: "Aushilfen",
        meaning: "Temporary help",
        english_sentence: "We're looking for a temp.",
        german_sentence: "Wir suchen eine Aushilfe.",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die", 
        wort: "Wand",
        plural: "Wände",
        meaning: "Wall",       
        english_sentence: "The picture is on the wall.",                 
        german_sentence: "Das Bild hängt an der Wand.",
        remark: "Dativ, Wo",
        chapter: "a2-2",
        create_date: "10/05/2022",
        update_date: "10/05/2022",            
    },
    { 
        artikel: "die",
        wort: "Wand",
        plural: "Wände",
        meaning: "Wall",
        english_sentence: "I hang the picture on the wall.",
        german_sentence: "Ich hänge das Bild an die Wand.",
        remark: "Akku, Wohin",
        chapter: "a2-2",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Lied",
        plural: "Lieder",
        meaning: "Song",
        english_sentence: "What do you think of the song?",
        german_sentence: "Wie findest du das Lied?",
        remark: "",
        chapter: "a2-4",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Erfahrung",
        plural: "-en",
        english_sentence: "Experiences in a foreign country",
        german_sentence: "Erfahrungen im fremden Land"
    },
    { 
        artikel: "der", 
        wort: "Teilnehmer",
        plural: "-",          
        english_sentence: "The participants in my course are almost always on time.",                 
        german_sentence: "Die Teilnehmer in meinem Kurs sind fast immer pünktlich."                 
    },
    { 
        artikel: "der", 
        wort: "Führerschein",
        plural: "-e",
        meaning: "driver's license",
        english_sentence: "I have lost my driver's license.",
        german_sentence: "Ich bin meinen Führerschein los.",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Führerscheinprüfung",
        plural: "-en",
        meaning: "driving test",
        english_sentence: "Have you passed your driving test?",
        german_sentence: "Hast du deine Führerscheinprüfung bestanden?",
        remark: "",
        chapter: "",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der", 
        wort: "Schulabschluss",
        plural: "-ü e",          
        english_sentence: "I have been with him since I got out of high school(graduation)",                 
        german_sentence: "Ich bin seit dem Schulabschluss bei ihm"                 
    },
    { 
        artikel: "der", 
        wort: "Motor",
        plural: "-en",          
        english_sentence: "I think the engine’s broken.",                 
        german_sentence: "Ich glaube, der Motor ist kaputt.",
        chapter: "a2-6",
    },
    { 
        artikel: "die",
        wort: "Reparatur",
        plural: "-en",
        meaning: "Repair",
        english_sentence: "the repair will be expensive.",
        german_sentence: "Die Reparatur wird bestimmt teuer.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Unfall",
        plural: "ä e",
        meaning: "Accident",
        english_sentence: "And what if I have an accident on vacation?",
        german_sentence: "Und was ist, wenn ich im Urlaub einen Unfall habe?",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die", 
        wort: "Versicherung",
        plural: "-en",          
        english_sentence: "Well, usually the insurance pays for it.",                 
        german_sentence: "Na ja, normalerweise bezahlt das die Versicherung.",
        chapter: "a2-6",           
    },
    { 
        artikel: "die",
        wort: "Reise",
        plural: "-n",
        meaning: "Travelling",
        english_sentence: "Travelling by train is too expensive for her, but she doesn’t have a car.",
        german_sentence: "Die Reise mit dem Zug ist ihr zu teuer, aber sie hat kein Auto",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Rad",
        plural: "ä er",
        meaning: "bike",
        english_sentence: "She likes to ride a bike",
        german_sentence: "Sie fährt gern Rad.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Kreis",
        plural: "-e",
        meaning: "circle",
        english_sentence: "You sit in a circle.",
        german_sentence: "Sie sitzen im Kreis.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Weg",
        plural: "-e",
        meaning: "circle",
        english_sentence: "The fast way through the city.",
        german_sentence: "Der schnelle Weg durch die Stadt.",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Lösung",
        plural: "-en",
        meaning: "solution",
        english_sentence: "We have the solution",
        german_sentence: "Wir haben die Lösung",
        remark: "",
        chapter: "a2-6",
        create_date: "10/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Wohnungsschlüssel",
        plural: "-",
        meaning: "Apartment key",
        english_sentence: "I forgot my apartment key!",
        german_sentence: "Ich habe meinen Wohnungsschlüssel vergessen!",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Verkehrsmittel",
        plural: "-",
        meaning: "Means of transport",
        english_sentence: "Which means of transport is the fastest?",
        german_sentence: "Welches Verkehrsmittel ist am schnellsten?",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Bushaltestelle",
        plural: "-n",
        meaning: "bus stop",
        english_sentence: "I’ve been waiting at the bus stop for half an hour.",
        german_sentence: "Ich warte schon eine halbe Stunde an der Bushaltestelle.",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Kinderspielplatz",
        plural: "-ä e",
        meaning: "children's playground",
        english_sentence: "Lilly and Felix must be at the children's playground.",
        german_sentence: "Lilly und Felix sind bestimmt auf dem Kinderspielplatz.",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Vertrag",
        plural: "-ä e",
        meaning: "contract, agreement",
        english_sentence: "none",
        german_sentence: "none",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Ersatzteil",
        plural: "e",
        meaning: "spare part",
        english_sentence: "none",
        german_sentence: "none",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Hochseilgarten",
        plural: "ä",
        meaning: "high ropes course",
        english_sentence: "The professionals from the high ropes course explain the rules to the people very well.",
        german_sentence: "Die Profis vom Hochseilgarten erklären den Leuten die Regeln sehr gut.",
        remark: "",
        chapter: "a2-6",
        create_date: "04/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Besucher",
        plural: "Besucher",
        meaning: "Visitor",
        english_sentence: "They give the visitors helmets.",
        german_sentence: "Sie geben den Besuchern Helme.",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Helm",
        plural: "Helme",
        meaning: "Helmet",
        english_sentence: "They give the visitors helmets.",
        german_sentence: "Sie geben den Besuchern Helme.",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Brief",
        plural: "Briefe",
        meaning: "letter",
        english_sentence: "Mrs.Korkmaz sends a letter to a man.",
        german_sentence: "Frau Korkmaz schickt einem Mann einen Brief.",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "das",
        wort: "Spielzeug",
        plural: "-",
        meaning: "toys",
        english_sentence: "Does Tom give his child a toy?",
        german_sentence: "Schenkt Tom seinem Kind ein Spielzeug?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Schal",
        plural: "Schals/Schale",
        meaning: "Scarf",
        english_sentence: "Does Tom give his mother a scarf?",
        german_sentence: "Schenkt Tom seiner Mutter einen Schal?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "der",
        wort: "Schminkspiegel",
        plural: "Schminkspiegel",
        meaning: "Makeup mirror",
        english_sentence: "Does Tom give his sister a make-up mirror?",
        german_sentence: "Schenkt Tom seiner Schwester einen Schminkspiegel?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
    { 
        artikel: "die",
        wort: "Marketasche",
        plural: "Marketaschen",
        meaning: "branded bag",
        english_sentence: "Does Tom give his wife a branded bag?",
        german_sentence: "Schenkt Tom seiner Frau eine Marketasche?",
        remark: "",
        chapter: "a2-8",
        create_date: "08/05/2022",
        update_date: "10/05/2022",
    },
]


module.exports = {
    words: words,
}